@url = http://localhost:3000/users

GET {{url}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInN1YiI6IjBkMjIxZTk4LTJjZjUtNDExMC1iNzYxLWE4YzVlZWU2ODBmMSIsImVtYWlsIjoibWJ1cnU4NTI2QGdtYWlsLmNvbSIsImlhdCI6MTc2NDU5MzU5NCwiZXhwIjoxNzY0Njc5OTk0fQ.c41Fgv0KV2EZ42n9JUKt_Oxxt3pYK46Jz0bb2sS4jVc
###
GET {{url}}/0d221e98-2cf5-4110-b761-a8c5eee680f1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsInN1YiI6IjBkMjIxZTk4LTJjZjUtNDExMC1iNzYxLWE4YzVlZWU2ODBmMSIsImVtYWlsIjoibWJ1cnU4NTI2QGdtYWlsLmNvbSIsImlhdCI6MTc2NDU5MzU5NCwiZXhwIjoxNzY0Njc5OTk0fQ.c41Fgv0KV2EZ42n9JUKt_Oxxt3pYK46Jz0bb2sS4jVc