@url = http://localhost:3000/auth

###
POST {{url}}/register
Content-Type: application/json

{
    "first_name": "Peter",
    "last_name": "Wahu",
    "email": "peterwahu3491@gmail.com",
    "password":"Phantom@8526"
}


###
POST {{url}}/login
Content-Type: application/json

{
    "email": "mburu8526@gmail.com",
    "password":"Phantom@852"
}

###
GET {{url}}